fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "contact@pâques.com"
        sender_name: "PÂQUES"

    change_password:
        form:
            type: AppBundle\Form\ChangePasswordType

    registration:
        confirmation:
            enabled: true


