fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "noreply@clictacoiffure.com"
        sender_name: "PÂQUES"

    resetting:
        email:
            template: emails/fos_user/reset-password.email.html.twig

    registration:
        confirmation:
            enabled: true
            template: emails/fos_user/registration_confirmation.email.html.twig


