nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        #max_age: 3600
        max_age: 0
    paths:
        '^/api':
            allow_origin: [ '^http://localhost:[0-9]+','^http://clictacoiffe.com' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH' ]
            max_age: 3600
        '^/free-api':
            allow_origin: [ '*' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST','PUT','GET','DELETE','PATCH' ]
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: [ '*' ]
            #allow_origin: [ '^http://localhost:[0-9]+', '^http://clictacoiffe.com' ]
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            #hosts: [ '^api\.' ]