fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user_registration_register:
  #path:      /account/register
  #defaults:  { _controller: FOSUserBundle:Registration:register, _method: POST }
  #arguments: []

#fos_user_security_login:
#  path:      /account/login
#  defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

#fos_user_registration_register:
#    path:      /account/register
#    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
    #resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    #prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile